package com.shop.enums;

public enum Products {
    BREAD, BUTTER, MILO, MILK, COOKIE, CORN_FLAKES,
    COKE, CWAY, MALTINA, BEER, WINE, SPRITE,
    TOILET_ROLL, SHAVING_STICK, TOOTHBRUSH, TOOTHPASTE, SANITARY_PAD, CREAM, DEODORANT, SOAP, TOWEL, FACIAL_TISSUE, WET_WIPE
}
